### PR TITLE
feat(customBreakpoints): custom breakpoints implementation

### PR DESCRIPTION
**Pull request by WiktorG**
I made a functionality of custom breakpoints. You can now pass number and media-queries are gonna be based on it.
I'm just pushing this out to see the diff 😄 

This is still work in progress - I'll let you know when it's done :)

### CODE REVIEW

**Comment by WiktorG** [comment]
In case anything changes - I haven't update readme yet. Let me know if everything is fine. I tested it and it works both with hooks and css-in-js.

**Comment by WiktorG** [comment]
Here is repo with working demo :) https://github.com/WiktorG/styled-custom-breakpoints-demo

**Comment by mg901** [comment]
@WiktorG Hi! First of all, I want to thank you for your interest in Styled Breakpoints. Before starting the development of Styled Breakpoints, I thought about the functionality you proposed, but this approach cannot exist on large projects, since the creation of such breakpoints will lead to house in the code. Sorry, I have to reject your PR.

**Comment by mg901** [comment]
In the future, if you have a desire to add any functionality to the library, you should create an issue with a description of the proposed API. And if the users of the library find it really useful and this will not break backward compatibility, it will be possible to create a PR with the implementation of the proposed functionality. This will save you a lot of your time. Once again, thank you for your interest in Styled Breakpoints.

**Comment by pawelwe** [comment]
Hi Maxim,
I think of this like a fallback to edge cases. 
It would be great to have it instead of adding just regular CSS media queries.
(especially useful in larger projects when you have some edge cases)

**Comment by WiktorG** [comment]
This was exactly what it was meant for! :) By default lib should use pre-defined breakpoints. 
We could mark that in the readme if you changed your mind @mg901
I think that if devs need to make tweaks in their project - they will 😅

So in my opinion this could be available for them within the library, 
instead of making custom media-queries that can get lost in big code-bases.

**Comment by mg901** [comment]
@WiktorG Ok, I see that such a need is ripe. You need to create an issue with the proposed API. If this feature is really needed in a large number of users, I will gladly add it.

**Comment by mg901** [comment]
@WiktorG Ok, I see that such a need is ripe for you or your team. However, first of all, it means that your designer made mistakes while designing the interface.
  You need to create an issue with the proposed API. If this feature is really needed in a large number of users, I will add it.

**Comment by WiktorG** [comment]
@mg901 Yes - exactly, but you know how it works 😄

Sometimes we don't get designs for all devices - mainly desktop, mobile. 
Tablets are often forgotten and we are stuck with media queries to make everything work. 😏

**Comment by WiktorG** [comment]
@mg901 I'll create issue and describe everything in there after my office-hours :D

**Pull request closed without merging**
